// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SZGC.Infrastructure.Data;

namespace SZGC.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220824082055_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SZGC.Domain.Models.Nomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCountTraverse")
                        .HasColumnType("int");

                    b.Property<double>("MaxWeightTraverse")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Nomenclatures");
                });

            modelBuilder.Entity("SZGC.Domain.Models.NomenclatureStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("StageId");

                    b.ToTable("NomenclatureStages");
                });

            modelBuilder.Entity("SZGC.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SZGC.Domain.Models.OrderNomenclature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AllWeight")
                        .HasColumnType("float");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderNomenclatures");
                });

            modelBuilder.Entity("SZGC.Domain.Models.OrderNomenclatureStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderNomenclatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderNomenclatureId");

                    b.HasIndex("StageId");

                    b.ToTable("OrderNomenclatureStages");
                });

            modelBuilder.Entity("SZGC.Domain.Models.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeExpired")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshSessions");
                });

            modelBuilder.Entity("SZGC.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3765b7d-3126-41f7-bbc4-f82b85aa6687"),
                            DateCreate = new DateTime(2022, 8, 24, 15, 20, 55, 121, DateTimeKind.Local).AddTicks(2434),
                            Name = "Root"
                        },
                        new
                        {
                            Id = new Guid("bd7533ab-39b4-4832-899c-220bb196fa00"),
                            DateCreate = new DateTime(2022, 8, 24, 15, 20, 55, 121, DateTimeKind.Local).AddTicks(2434),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("SZGC.Domain.Models.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortedBy")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("SZGC.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CountFailEnter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UpdatePassword")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd19b431-a9c5-4883-b436-227e817f5d7b"),
                            Active = true,
                            CountFailEnter = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "Root",
                            MiddleName = "Root",
                            Name = "Root",
                            Password = "G1GrIyE+HaeVNwCvwhONvpUrdkaVGcNyLQqBuYvS6cs=",
                            Salt = new byte[] { 41, 160, 18, 37, 236, 175, 123, 173, 186, 170, 70, 29, 11, 117, 20, 95 },
                            SurName = "Root",
                            UpdatePassword = false
                        },
                        new
                        {
                            Id = new Guid("8d79f660-70cf-4895-bd5c-51ed5981812c"),
                            Active = true,
                            CountFailEnter = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "duser",
                            MiddleName = "",
                            Name = "User",
                            Password = "CiTnTw+aw0NuNr9ynK5c4i2ge7iTYc07OfQPtperlbI=",
                            Salt = new byte[] { 41, 160, 18, 37, 236, 175, 123, 173, 186, 170, 70, 29, 11, 117, 20, 95 },
                            SurName = "Default",
                            UpdatePassword = false
                        });
                });

            modelBuilder.Entity("SZGC.Domain.Models.UserChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("UpdatePassword")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserChanges");
                });

            modelBuilder.Entity("SZGC.Domain.Models.UserChangeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserChangeType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e8dc80d-7b4f-417f-9993-775bba0c0fb0"),
                            DateCreate = new DateTime(2022, 8, 24, 15, 20, 55, 122, DateTimeKind.Local).AddTicks(2467),
                            Name = "Добавление пользователя"
                        },
                        new
                        {
                            Id = new Guid("528c3373-8b1e-4ab8-99c0-1413ea91b299"),
                            DateCreate = new DateTime(2022, 8, 24, 15, 20, 55, 122, DateTimeKind.Local).AddTicks(2467),
                            Name = "Изменение пользователя"
                        },
                        new
                        {
                            Id = new Guid("5d5e5f0b-3af1-4767-b268-452cff940404"),
                            DateCreate = new DateTime(2022, 8, 24, 15, 20, 55, 122, DateTimeKind.Local).AddTicks(2467),
                            Name = "Удаление пользователя"
                        });
                });

            modelBuilder.Entity("SZGC.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("c3765b7d-3126-41f7-bbc4-f82b85aa6687"),
                            UserId = new Guid("cd19b431-a9c5-4883-b436-227e817f5d7b")
                        },
                        new
                        {
                            RoleId = new Guid("bd7533ab-39b4-4832-899c-220bb196fa00"),
                            UserId = new Guid("8d79f660-70cf-4895-bd5c-51ed5981812c")
                        });
                });

            modelBuilder.Entity("SZGC.Domain.Models.Nomenclature", b =>
                {
                    b.HasOne("SZGC.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SZGC.Domain.Models.NomenclatureStage", b =>
                {
                    b.HasOne("SZGC.Domain.Models.Nomenclature", "Nomenclature")
                        .WithMany("NomenclatureStages")
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SZGC.Domain.Models.Stage", "Stage")
                        .WithMany("NomenclatureStages")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SZGC.Domain.Models.Order", b =>
                {
                    b.HasOne("SZGC.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SZGC.Domain.Models.OrderNomenclature", b =>
                {
                    b.HasOne("SZGC.Domain.Models.Nomenclature", "Nomenclature")
                        .WithMany("OrderNomenclatures")
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SZGC.Domain.Models.Order", "Order")
                        .WithMany("OrderNomenclatures")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SZGC.Domain.Models.OrderNomenclatureStage", b =>
                {
                    b.HasOne("SZGC.Domain.Models.OrderNomenclature", "OrderNomenclature")
                        .WithMany("OrderNomenclatureStages")
                        .HasForeignKey("OrderNomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SZGC.Domain.Models.Stage", "Stage")
                        .WithMany("OrderNomenclatureStages")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SZGC.Domain.Models.RefreshSession", b =>
                {
                    b.HasOne("SZGC.Domain.Models.User", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SZGC.Domain.Models.Stage", b =>
                {
                    b.HasOne("SZGC.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SZGC.Domain.Models.UserChange", b =>
                {
                    b.HasOne("SZGC.Domain.Models.User", "Owner")
                        .WithMany("OwnerChanges")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SZGC.Domain.Models.UserChangeType", "Type")
                        .WithMany("UserChanges")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SZGC.Domain.Models.User", "User")
                        .WithMany("UserChanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SZGC.Domain.Models.UserRole", b =>
                {
                    b.HasOne("SZGC.Domain.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SZGC.Domain.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
